-- ================================================
-- Supabase 云端数据库建表脚本（完整建站版）
-- 使用：Supabase → SQL Editor → New query → 粘贴本文件全部内容 → Run
-- ================================================

-- 1. 任务表（倒计时任务，目标时间统一为北京时间）
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  name text not null,
  target_beijing_time timestamptz not null,
  created_at timestamptz default now()
);

-- 2. 登录日志表（记录账号、输入密码、IP、国家/地区、登录结果、时间）
create table if not exists public.login_logs (
  id bigint generated by default as identity primary key,
  email text,
  input_pwd text,
  ip text,
  area text,
  status text,
  created_at timestamptz default now()
);

-- 3. 打开行级安全（后端用 service_role 密钥读写，不受 RLS 限制）
alter table public.tasks enable row level security;
alter table public.login_logs enable row level security;

-- 4. 可选：任务表策略（供 anon/authenticated 直连时的兜底控制，非必需）
--    create policy tasks_admin_all on public.tasks for all
--      using (auth.jwt() ->> 'email' = '1757349561@qq.com');
--    create policy tasks_user_select on public.tasks for select using (true);
